# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dropbox\Software\radioblock\sniffer_project\sniffer2.ui'
#
# Created: Tue Apr 30 22:50:41 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 578)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/cmd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolbar {\n"
"background-image: url(./images/colorado.jpg)}\n"
"\n"
"QLabel#board { color: yellow; background-color:#ffff99\n"
"; border:2px solid white; border-radius: 8px; border-bottom-color: grey; border-right-color:black;padding-bottom:5px; font:bold}\n"
"\n"
"QToolButton { color: yellow; background-color:#ffff99\n"
"; border:2px solid white; border-radius: 8px; border-bottom-color: grey; border-right-color:black;padding-bottom:5px; font:bold}\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"background-color:     #FFff00;\n"
"\n"
"}\n"
"\n"
"QToolButton:pressed#toolButtonBoard\n"
"{\n"
"background-color:     #FFff99;\n"
"\n"
"}\n"
"\n"
"")
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(1100, 50))
        self.widget.setMaximumSize(QtCore.QSize(1100, 50))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.toolButtonConnect = QtGui.QToolButton(self.widget)
        self.toolButtonConnect.setGeometry(QtCore.QRect(157, 10, 61, 41))
        self.toolButtonConnect.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonConnect.setIcon(icon1)
        self.toolButtonConnect.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonConnect.setAutoRaise(True)
        self.toolButtonConnect.setObjectName("toolButtonConnect")
        self.comboBoxPorts = QtGui.QComboBox(self.widget)
        self.comboBoxPorts.setGeometry(QtCore.QRect(67, 23, 81, 25))
        self.comboBoxPorts.setObjectName("comboBoxPorts")
        self.toolButtonPlay = QtGui.QToolButton(self.widget)
        self.toolButtonPlay.setGeometry(QtCore.QRect(228, 10, 61, 41))
        self.toolButtonPlay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPlay.setIcon(icon2)
        self.toolButtonPlay.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonPlay.setAutoRaise(True)
        self.toolButtonPlay.setObjectName("toolButtonPlay")
        self.toolButtonTrash = QtGui.QToolButton(self.widget)
        self.toolButtonTrash.setGeometry(QtCore.QRect(371, 10, 61, 41))
        self.toolButtonTrash.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonTrash.setIcon(icon3)
        self.toolButtonTrash.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonTrash.setAutoRaise(False)
        self.toolButtonTrash.setObjectName("toolButtonTrash")
        self.toolButtonPause = QtGui.QToolButton(self.widget)
        self.toolButtonPause.setGeometry(QtCore.QRect(299, 10, 61, 41))
        self.toolButtonPause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPause.setIcon(icon4)
        self.toolButtonPause.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonPause.setObjectName("toolButtonPause")
        self.toolButtonFilter = QtGui.QToolButton(self.widget)
        self.toolButtonFilter.setGeometry(QtCore.QRect(443, 10, 61, 41))
        self.toolButtonFilter.setWhatsThis("")
        self.toolButtonFilter.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonFilter.setIcon(icon5)
        self.toolButtonFilter.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonFilter.setShortcut("")
        self.toolButtonFilter.setObjectName("toolButtonFilter")
        self.toolButtonBoard = QtGui.QToolButton(self.widget)
        self.toolButtonBoard.setGeometry(QtCore.QRect(3, 10, 51, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBoard.setIcon(icon6)
        self.toolButtonBoard.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonBoard.setAutoRaise(True)
        self.toolButtonBoard.setObjectName("toolButtonBoard")
        self.toolButtonExit = QtGui.QToolButton(self.widget)
        self.toolButtonExit.setGeometry(QtCore.QRect(1018, 10, 61, 41))
        self.toolButtonExit.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/exit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExit.setIcon(icon7)
        self.toolButtonExit.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonExit.setObjectName("toolButtonExit")
        self.comboBoxField = QtGui.QComboBox(self.widget)
        self.comboBoxField.setGeometry(QtCore.QRect(516, 25, 111, 22))
        self.comboBoxField.setObjectName("comboBoxField")
        self.toolButtonLog = QtGui.QToolButton(self.widget)
        self.toolButtonLog.setGeometry(QtCore.QRect(878, 10, 61, 41))
        self.toolButtonLog.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonLog.setIcon(icon8)
        self.toolButtonLog.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonLog.setObjectName("toolButtonLog")
        self.comboBoxChannel = QtGui.QComboBox(self.widget)
        self.comboBoxChannel.setGeometry(QtCore.QRect(799, 26, 69, 22))
        self.comboBoxChannel.setObjectName("comboBoxChannel")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.setItemText(0, "")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.comboBoxChannel.addItem("")
        self.toolButtonFilterClear = QtGui.QToolButton(self.widget)
        self.toolButtonFilterClear.setGeometry(QtCore.QRect(727, 10, 61, 41))
        self.toolButtonFilterClear.setWhatsThis("")
        self.toolButtonFilterClear.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/filtercancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonFilterClear.setIcon(icon9)
        self.toolButtonFilterClear.setIconSize(QtCore.QSize(64, 64))
        self.toolButtonFilterClear.setShortcut("")
        self.toolButtonFilterClear.setObjectName("toolButtonFilterClear")
        self.label = QtGui.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(515, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(636, 9, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(798, 12, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(67, 9, 81, 16))
        self.label_4.setObjectName("label_4")
        self.lineEditValue = QtGui.QLineEdit(self.widget)
        self.lineEditValue.setGeometry(QtCore.QRect(636, 24, 81, 22))
        self.lineEditValue.setObjectName("lineEditValue")
        self.toolAbout = QtGui.QToolButton(self.widget)
        self.toolAbout.setGeometry(QtCore.QRect(948, 10, 61, 41))
        self.toolAbout.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/help-hint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolAbout.setIcon(icon10)
        self.toolAbout.setIconSize(QtCore.QSize(64, 64))
        self.toolAbout.setObjectName("toolAbout")
        self.verticalLayout_3.addWidget(self.widget)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableView = QtGui.QTableView(self.splitter)
        self.tableView.setStyleSheet("QTableView {selection-background-color: #FFff00; selection-color: black}")
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.toolButtonExit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SimpleMesh Sniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonConnect.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Open/Close selected serial port</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPlay.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Start logging data</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonTrash.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Clear all data</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPause.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Pause log</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFilter.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Filter Frames by PANID, NWK address, etc.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonBoard.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonExit.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Exit application</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonLog.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Create log file</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(1, QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(2, QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(3, QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(4, QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(5, QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(6, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(7, QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(8, QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(9, QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(10, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(11, QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(12, QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(13, QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(14, QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChannel.setItemText(15, QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFilterClear.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Reset filter</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Filter Field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Filter Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Set Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "COM port", None, QtGui.QApplication.UnicodeUTF8))
        self.toolAbout.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>About sm_sniffer</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Frame Information", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

